# Generated by Django 5.1.4 on 2025-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('text', models.CharField(max_length=999)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
