# Generated by Django 5.1.4 on 2025-01-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Темы', 'verbose_name_plural': 'Темы'},
        ),
    ]
