# Generated by Django 5.1.4 on 2025-01-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_poste_alter_post_id_alter_post_name_alter_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Темы', 'verbose_name_plural': 'АЭМ'},
        ),
        migrations.AlterModelOptions(
            name='poste',
            options={'verbose_name': 'Темы', 'verbose_name_plural': 'ЭОВС'},
        ),
    ]
