# Generated by Django 5.1.4 on 2025-01-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_posts_alter_poste_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Postw',
        ),
    ]
