# Generated by Django 5.1.4 on 2025-01-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_accesskey_assigned_name_accesskey_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagess/'),
        ),
    ]
