# Generated by Django 5.1.4 on 2025-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_post_image_alter_postw_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessKey',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='postw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagess'),
        ),
    ]
