# Generated by Django 5.1.5 on 2025-02-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_comment_commente_commentw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commente',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentse', to='app1.poste'),
        ),
        migrations.AlterField(
            model_name='commentw',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsw', to='app1.postw'),
        ),
    ]
